# Neural Network classification with pyTorch

## 1. Making Data

In [1]:
import sklearn
from sklearn.datasets import make_circles
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import torch
from torch import nn
import ipywidgets

In [2]:
# Make 1000 samples
n_samples = 1000

X, y = make_circles(n_samples,
                    noise=0.03,
                    random_state=42)
# Create circle
def cir_plot(noise):
  X, y = make_circles(n_samples,
                      noise=noise,
                      random_state=42)
  plt.style.use('dark_background')
  plt.scatter(x=X[:, 0],
              y=X[:, 1],
              c=y,
              cmap=plt.cm.RdYlBu)

In [3]:
ipywidgets.interact(cir_plot, noise=(0, 1, 0.01))

interactive(children=(FloatSlider(value=0.0, description='noise', max=1.0, step=0.01), Output()), _dom_classes…

<function __main__.cir_plot(noise)>

In [4]:
len(X), len(y)

(1000, 1000)

In [5]:
X.shape, y.shape

((1000, 2), (1000,))

In [6]:
X[:3], y[:3]

(array([[ 0.75424625,  0.23148074],
        [-0.75615888,  0.15325888],
        [-0.81539193,  0.17328203]]),
 array([1, 1, 1]))

In [7]:
circles = pd.DataFrame({"X1": X[:, 0],
                        "X2": X[:, 1],
                          "Label": y})
circles.head()

,X1,X2,Label
0,0.754246,0.231481,1
1,-0.756159,0.153259,1
2,-0.815392,0.173282,1
3,-0.393731,0.692883,1
4,0.442208,-0.896723,0


### 1.1 Check input and output shapes

In [8]:
X[:, :4]

array([[ 0.75424625,  0.23148074],
       [-0.75615888,  0.15325888],
       [-0.81539193,  0.17328203],
       ...,
       [-0.13690036, -0.81001183],
       [ 0.67036156, -0.76750154],
       [ 0.28105665,  0.96382443]])

In [9]:
# View the first example of features and labels
X_sample = X[0]
y_sample = y[0]
print(f'Value for single sample of X: {X_sample}, and the same for y: {y_sample}')
print(f'Shape for single sample of X: {X_sample.shape}, and the same for y: {y_sample.shape}')

Value for single sample of X: [0.75424625 0.23148074], and the same for y: 1
Shape for single sample of X: (2,), and the same for y: ()


### 1.2 Turn data into tensor and create train and test splits

In [10]:
type(X)

numpy.ndarray

In [11]:
# Turn data into tensors
X = torch.from_numpy(X).type(torch.float)
y = torch.from_numpy(y).type(torch.float)
X[:3], y[:3]

(tensor([[ 0.7542,  0.2315],
         [-0.7562,  0.1533],
         [-0.8154,  0.1733]]),
 tensor([1., 1., 1.]))

In [12]:
type(X), X.dtype, y.dtype

(torch.Tensor, torch.float32, torch.float32)

In [13]:
# Split data into train and test set
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size=0.2,
                                                    random_state=42)


In [14]:
len(X_train), len(X_test)

(800, 200)